name: Build and Test Java

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Compile Java files
        run: javac -d out FileEncryptionApp/src/*.java

      - name: Run Java application
        run: java -cp out FileEncryptionApp
